//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalleDataFirstEFWpfApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Productoes = new ObservableCollection<Productoes>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ObservableCollection<Productoes> Productoes { get; set; }
    }
}
