//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingDBLearningWpfApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Enrollments = new ObservableCollection<Enrollments>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Duration { get; set; }
        public string Description { get; set; }
        public int SubjectID { get; set; }
        public int TutorID { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Tutors Tutors { get; set; }
        public virtual ObservableCollection<Enrollments> Enrollments { get; set; }
    }
}
