//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingDBLearningWpfApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Tutors
    {
        public Tutors()
        {
            this.Courses = new ObservableCollection<Courses>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual ObservableCollection<Courses> Courses { get; set; }
    }
}
